### ISSUE TITLE
Final capstone project Kanban board setup.

### ISSUE THREAD

**Issue by Nasirkhan294** [Nasirkhan294/final-capstone-back-end#11]
### Kanban board visual:
![kanban board](https://github.com/Nasirkhan294/final-capstone-back-end/assets/71121832/7f62a74d-4a62-4f9c-a199-e4a7e7bc9d8e)

![kanban board1](https://github.com/Nasirkhan294/final-capstone-back-end/assets/71121832/bc017497-a688-4c29-b385-b44de57dfd11)

**Comment by Meltrust** [comment]
Hi @Nasirkhan294,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Tasks have assignees, descriptions, and pointings.  The pointings are fair according to the spec. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nasirkhan294** [comment]
Hi @Meltrust, Thanks for the approval.
